# Railway.app Configuration for Backstage Pass
# Deployment: Connect GitHub repo and Railway auto-deploys on push to main

[build]
builder = "DOCKER"

[deploy]
startCommand = "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 3