default:
  models:
    Billing::Purchase: read
    AccessPassExperience: read
    AccessPass: read
    Experience: read
    Space: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

viewer:
  models:
    AccessPass: read
    Experience: read
    Space: read
    Team: read
    Membership: read

buyer:
  # Buyers can only see what they've purchased
  # Their actual permissions come from AccessGrant records
  models:
    Space: read
    AccessPass: read
    Experience: read
    AccessGrant: read
    Billing::Purchase: read
    Team: read
    Membership: read

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
    - viewer
  manageable_roles:
    - admin
    - editor
    - viewer
    - buyer
  models:
    Billing::Purchase: manage
    AccessPassExperience: manage
    AccessPass: manage
    Experience: manage
    Space: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
